# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.
#
# If you need help with YAML syntax, here are some quick references for you:
# https://learn-the-web.algonquindesign.ca/topics/markdown-yaml-cheat-sheet/#yaml
# https://learnxinyminutes.com/docs/yaml/
#
# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.

title: Samuel C. Hoover
repository: samuelhoover/samuelhoover.github.io
logo: "../assets/imgs/IMG_6988-cropped.png?raw=true"
description: >
  <br>
  Chemical engineering Ph.D., PPG Fellow, polymer physicist, and computational 
  modeler.
  <br><br>
  <a href="/projects/">Projects</a> <br>
  <a href="/assets/pdfs/cv.pdf">CV</a> | <a href="/assets/pdfs/resume.pdf">Resume</a>
  <br><br>

  <a href="mailto:samuelhoover@umass.edu">
  <img style="padding: 0px 10px 0px 0px;" src="/assets/imgs/mail.png" height="32"/>
  </a>
  <a href="https://github.com/samuelhoover">
  <img style="padding: 0px 10px 0px 0px;" src="/assets/imgs/github-mark.png" height="32"/>
  </a>
  <a href="https://linkedin.com/in/samuel-hoover">
  <img style="padding: 0px 10px 0px 0px;" src="/assets/imgs/linkedin.png" height="32"/>
  </a>

url: https://samuelhoover.github.io # the base hostname & protocol for your site, e.g. http://example.com

github:
  is_project_page: false

# Build settings
# theme: minima
remote_theme: pages-themes/minimal@v0.2.0
plugins:
  - jekyll-remote-theme
# Exclude from processing.
# The following items will not be processed, by default.
# Any item listed under the `exclude:` key here will be automatically added to
# the internal "default list".
#
# Excluded items can be processed by explicitly listing the directories or
# their entries' file path in the `include:` list.
#
# exclude:
#   - .sass-cache/
#   - .jekyll-cache/
#   - gemfiles/
#   - Gemfile
#   - Gemfile.lock
#   - node_modules/
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/
